### PR TITLE
feat: ✨ Add fancy background

### PR DESCRIPTION
**Pull request by EchelonFour**
Recording 2023-05-18 at 22 37 03
It does not render as bad as that GIF.

Does some parallax stuff via a plugin.
I picked a bunch of Z axis values that are nebulous. I think a decision about what ranges each class of asset get along the z axis are needed. (eg player is 100 and other stuff is above or below that or whatever)

> "But texture assets break my visual design!!!"

Yes, but rendering the complexity of a starfield is too much if each dot is a component. If you wanna dump the nebula background, then I guess. But I think it looks pretty.

### CODE REVIEW

**Comment by JamesHDuffield** [comment]
I agree it looks pretty, and I'm not against using assets for that stuff.

I do think it is visually distracting at the settings you have there. I played around with speed 0.95 for the nebula and 0.9 for the stars and that looked more "realistic" and less distracting.

I suggest something like the following:

```
enum RenderLayer {
  DeepBackground: 0.0
  Background: 0.1
  Bullet: 0.3
  Player: 0.5
  Enemy: 0.6
  Effects: 0.8
  Overlay: 1.0
}
```

**Comment by EchelonFour** [comment]
I picked 0 for the stars because there is no visual reference for how fast you are actually moving. I wanted a fixed background.
If you would rather they move slower, then ok.

I'm gonna multiply all those numbers by 100, but I can make that enum

**Comment by JamesHDuffield** [comment]
I think if there is a visual reference it should be a component that is intractable/collidable.

**Comment by EchelonFour** [comment]
@JamesHDuffield Ready to go i reckon
Had to trancate a bunch of collision vector math. Otherwise the distance was being calculated on the z axis too.

**Pull request merged**
